apiVersion: v1
kind: ConfigMap
metadata:
  name: gtd-backend-config
  namespace: gtd-system
  labels:
    app.kubernetes.io/name: gtd-backend
    app.kubernetes.io/component: configmap
data:
  config.yaml: |
    app:
      name: "GTD Backend API"
      version: "1.0.0"
      environment: "production"
      debug: false

    server:
      host: "0.0.0.0"
      port: 8000

    database:
      supabase:
        url: ""
        anon_key: ""
        service_role_key: ""
      postgres:
        url: ""
      test:
        url: "sqlite+aiosqlite:///:memory:"

    security:
      secret_key: "your-secret-key-here-change-in-production"
      algorithm: "HS256"
      access_token_expire_minutes: 60

    cors:
      origins: ["*"]
      allow_credentials: true
      allow_methods: ["*"]
      allow_headers: ["*"]

    api:
      prefix: "/api"
      docs_url: null
      redoc_url: null
      openapi_url: null

    logging:
      level: "INFO"
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    pagination:
      default_limit: 50
      max_limit: 1000

    gtd:
      default_user_id: "00000000-0000-0000-0000-000000000001"
      tasks:
        priorities: [1, 2, 3, 4, 5]
        default_priority: 3
      projects:
        auto_create_fields: true
      weekly_review:
        enabled: true

    features:
      authentication_enabled: true
      real_time_updates: false
      email_notifications: false
      export_import: true