apiVersion: v1
kind: Secret
metadata:
  name: gtd-backend-secrets
  namespace: gtd-system
  labels:
    app.kubernetes.io/name: gtd-backend
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # To encode: echo -n "your-value" | base64
  
  # Database connection
  POSTGRES_URL: ""  # postgresql+asyncpg://user:password@host:5432/database
  
  # Supabase (if using)
  SUPABASE_URL: ""  # https://your-project.supabase.co
  SUPABASE_SERVICE_ROLE_KEY: ""  # your-service-role-key
  
  # Security
  SECRET_KEY: ""  # your-secret-key-at-least-32-characters
  
  # Additional secrets as needed
  JWT_SECRET: ""
---
# Example of how to create secrets from command line:
# kubectl create secret generic gtd-backend-secrets \
#   --from-literal=POSTGRES_URL="postgresql+asyncpg://user:password@host:5432/database" \
#   --from-literal=SUPABASE_URL="https://your-project.supabase.co" \
#   --from-literal=SUPABASE_SERVICE_ROLE_KEY="your-service-role-key" \
#   --from-literal=SECRET_KEY="your-very-long-secret-key-here" \
#   --namespace=gtd-system