# GTD Backend Configuration Template
# Copy this file to config.yaml and update with your actual values

# Application Settings
app:
  name: "GTD Backend API"
  version: "0.1.0"
  environment: "development"
  debug: true

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000

# Database Configuration
database:
  # Supabase configuration
  supabase:
    url: "https://your-project.supabase.co"
    service_role_key: "your-service-role-key"
  
  # Use IPv4 pooler for reliable connection
  postgres:
    url: "postgresql+asyncpg://postgres.your-project:your-service-role-key@aws-0-us-east-1.pooler.supabase.com:5432/postgres"
  
  # Test database (use same as postgres for development)
  test:
    url: "postgresql+asyncpg://postgres.your-project:your-service-role-key@aws-0-us-east-1.pooler.supabase.com:5432/postgres"

# Security Configuration
security:
  secret_key: "dev-secret-key-change-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# CORS Configuration
cors:
  origins:
    - "http://localhost:3000"  # Next.js frontend
    - "http://localhost:8000"  # Backend docs
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8000"
  allow_credentials: true
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATCH"
    - "OPTIONS"
  allow_headers:
    - "*"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# API Configuration
api:
  prefix: "/api"
  docs_url: "/api/docs"
  redoc_url: "/api/redoc"
  openapi_url: "/api/openapi.json"

# Pagination Configuration
pagination:
  default_limit: 50
  max_limit: 200

# GTD Configuration
gtd:
  default_user_id: "00000000-0000-0000-0000-000000000001"
  tasks:
    max_per_project: 500
    default_priority: 3
  projects:
    max_per_user: 1000
    archive_after_days: 365
  weekly_review:
    enabled: true
    day_of_week: "sunday"

# Features Configuration
features:
  authentication_enabled: false
  real_time_updates: false
  email_notifications: false
  export_import: true